export enum TokenType {
  VERIFY = 'VERIFY',
  AUTH = 'AUTH',
  JUDGEEVALUATION = 'JUDGEEVALUATION'
}

export enum UserTypes {
  TALENT = 'TALENT',
  PROFESSIONAL = 'PROFESSIONAL',
  AUDIENCE = 'AUDIENCE'
}
